import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/sharedcomponent/Navbar";
import JoinDeeUniqueFamily from "@/components/landingpage/JoinDeeUniqueFamily";
import Footer from "@/components/sharedcomponent/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Choose your desired font weights
  variable: "--font-poppins", // Create a CSS variable
});

export const metadata: Metadata = {
  title: "Dee Unique ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Navbar href={""} />
        <main>{children}</main>
        <JoinDeeUniqueFamily />
        <Footer />
      </body>
    </html>
  );
}
